name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric

info:
  Version: 2.2.4
  Size: 2 Orgs with 1 Peer each
  Orderer: Raft (Single Orderer)
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/hfc-kvs/org1
        cryptoStore:
          path: /tmp/hfc-cvs/org1
      clientPrivateKey:
        path: /home/eranda/v2x-net/org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/8b97b51627ce3d8a6ed8233eeba8d562d1b1d6897befac4d46ae171eeafc4cf0_sk
      clientSignedCert:
        path: /home/eranda/v2x-net/org1/crypto-config-ca/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/cert.pem

  client0.org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/hfc-kvs/org2
        cryptoStore:
          path: /tmp/hfc-cvs/org2
      clientPrivateKey:
        path: /home/eranda/v2x-net/org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/keystore/a93d3aec25738f9fea9694d7b55972cf9139f2233e4aa015b7f8d940131ef2cf_sk
      clientSignedCert:
        path: /home/eranda/v2x-net/org2/crypto-config-ca/peerOrganizations/org2.example.com/users/User1@org2.example.com/msp/signcerts/cert.pem

channels:
  mychannel:
    created: true
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        eventSource: true
      peer0.org2.example.com:
        eventSource: true

    contracts:
      - id: overtakingcc
        version: "1"
        language: golang

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com
    adminPrivateKey:
      path: /home/eranda/v2x-net/org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/340fe681e051a647ded57afbb2b80ea6a5465222e356f6be208abd6b6305e6fc_sk
    signedCert:
      path: /home/eranda/v2x-net/org1/crypto-config-ca/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/cert.pem

  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
    certificateAuthorities:
      - ca.org2.example.com
    adminPrivateKey:
      path: /home/eranda/v2x-net/org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/e4f5b12d4843eb134eda622ce14e002559424d9468ced66b3a671e1431bec1c6_sk
    signedCert:
      path: /home/eranda/v2x-net/org2/crypto-config-ca/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/cert.pem

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.example.com
    tlsCACerts:
      path: /home/eranda/v2x-net/orderer/crypto-config-ca/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/eranda/v2x-net/org1/crypto-config-ca/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/tls-localhost-7054-ca-org1-example-com.pem

  peer0.org2.example.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /home/eranda/v2x-net/org2/crypto-config-ca/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/tlscacerts/tls-localhost-8054-ca-org2-example-com.pem

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/eranda/v2x-net/org1/crypto-config-ca/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw

  ca.org2.example.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: /home/eranda/v2x-net/org2/crypto-config-ca/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
